package interfaz;


/**
* interfaz/PeerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Javier/Universidad/NetBeans Projects/BullyCorba/src/peer.idl
* viernes 29 de abril de 2022 12:32:58 PM CDT
*/

abstract public class PeerHelper
{
  private static String  _id = "IDL:interfaz/Peer:1.0";

  public static void insert (org.omg.CORBA.Any a, interfaz.Peer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static interfaz.Peer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (interfaz.PeerHelper.id (), "Peer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static interfaz.Peer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PeerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, interfaz.Peer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static interfaz.Peer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof interfaz.Peer)
      return (interfaz.Peer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      interfaz._PeerStub stub = new interfaz._PeerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static interfaz.Peer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof interfaz.Peer)
      return (interfaz.Peer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      interfaz._PeerStub stub = new interfaz._PeerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
