package interfaz;


/**
* interfaz/Peer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Javier/Universidad/NetBeans Projects/BullyCorba/src/peer.idl
* viernes 29 de abril de 2022 12:32:58 PM CDT
*/

public interface Peer extends PeerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Peer
