package interfaz;


/**
* interfaz/PeerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Javier/Universidad/NetBeans Projects/BullyCorba/src/peer.idl
* viernes 29 de abril de 2022 12:32:58 PM CDT
*/

public interface PeerOperations 
{
  void enviarHora (int id, String msj);
  void enviarMensaje (int id, String msj);
  void coordinador ();
} // interface PeerOperations
