package interfaz;


/**
* interfaz/Peer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Javier/Universidad/NetBeans Projects/PeerToPeerCorba/src/peer.idl
* miércoles 27 de abril de 2022 07:02:17 PM CDT
*/

public interface Peer extends PeerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Peer
