package interfaz;


/**
* interfaz/PeerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Javier/Universidad/NetBeans Projects/PeerToPeerCorba/src/peer.idl
* miércoles 27 de abril de 2022 07:02:17 PM CDT
*/

public interface PeerOperations 
{
  void enviar_Mensaje (String msj);
  void shutdown ();
} // interface PeerOperations
