package interfaz.PeerPackage;


/**
* interfaz/PeerPackage/petHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Javier/Universidad/NetBeans Projects/LectorEscritorCorba/src/peer.idl
* miércoles 4 de mayo de 2022 06:18:06 PM CDT
*/

public final class petHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public petHolder ()
  {
  }

  public petHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = interfaz.PeerPackage.petHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    interfaz.PeerPackage.petHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return interfaz.PeerPackage.petHelper.type ();
  }

}
