package interfaz;


/**
* interfaz/Peer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Javier/Universidad/NetBeans Projects/LectorEscritorCorba/src/peer.idl
* miércoles 4 de mayo de 2022 06:18:06 PM CDT
*/

public interface Peer extends PeerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Peer
