package interfaz;


/**
* interfaz/PeerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Javier/Universidad/NetBeans Projects/LectorEscritorCorba/src/peer.idl
* miércoles 4 de mayo de 2022 06:18:06 PM CDT
*/

public interface PeerOperations 
{
  boolean coordinador ();
  boolean lector ();
  boolean working ();
  void changeWorking ();
  void actualizarPeticiones (String[] lectores, String[] escritores);
  String[] obtenerPeticioneslector ();
  String[] obtenerPeticionesescritor ();
} // interface PeerOperations
